# Spring of Code - Artificial Intelligence
## Week 04: Exploratory Data Analysis
### Day 01: Introduction to Numpy

In this notebook, we will learn about **Numpy Arrays and Common Operations**.

# Installing Numpy (or any other package)
To install Numpy, you can use the following command:
`pip install numpy`

In [ ]:
!pip install numpy

## But What is a Package?
A Python package is a collection of related modules (Python files) organized in a directory with an `__init__.py` file.


In [1]:
# Check Installation
import numpy

numpy.__version__

'2.2.6'

In [179]:
import numpy as np
np.__version__

'2.2.6'

# What is NumPy?

- NumPy is the fundamental package for numerical computing in Python.
- Provides the `ndarray` (n-dimensional array) for fast, vectorized operations.
- Written in C under the hood for performance; operations run much faster than pure Python loops.

## NumPy arrays vs Python lists

- Fixed-type, contiguous memory vs. variable-type, object arrays.
- Vectorized operations (element-wise) vs. explicit Python loops.
- Rich slicing, indexing, and memory views.


In [3]:
numbers_list = list(range(1000000))
numbers_array = np.array(numbers_list)

In [4]:
type(numbers_list)

list

In [5]:
type(numbers_array)

numpy.ndarray

In [6]:
import time
time.time()

1773045422.5237856

In [7]:
# Calculating execution time for list operation
start_time = time.time()
sum_of_list = sum(numbers_list)
end_time = time.time()

list_exec_time = end_time - start_time

# Calculating execution time for numpy array operation
start_time = time.time()
sum_of_list = np.sum(numbers_array)
end_time = time.time()

arr_exec_time = end_time - start_time


print(f"List operation: {list_exec_time:.5f}")
print(f"Array operation: {arr_exec_time:.5f}")

List operation: 0.02755
Array operation: 0.00099


# Creating NumPy arrays

You can create arrays from Python lists, or using NumPy's array-creation utilities.


In [8]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [9]:
type(arr)

numpy.ndarray

In [10]:
a_list = [1, 2, 3, 4]
arr = np.array(a_list)
arr

array([1, 2, 3, 4])

In [11]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(2,10,3)
arr

array([2, 5, 8])

In [18]:
# array of zeros (0)
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2, 5), 7)

array([7, 7])

In [25]:
np.full(4, 5)

array([5, 5, 5, 5])

In [26]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random arrays

In [180]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x28B7533F220

In [37]:
rng.random((2, 3))

array([[0.12150747, 0.78953137, 0.87615553],
       [0.33063043, 0.98978866, 0.80369093]])

In [40]:
rng.integers(0, 10, (2, 3))

array([[7, 9, 3],
       [1, 8, 0]])

## Array attributes and reshaping

Key attributes:
- `ndim`: number of dimensions
- `shape`: size along each dimension
- `size`: total number of elements
- `dtype`: data type of elements

Reshaping changes the view of the data without changing the underlying memory when possible.


In [44]:
arr = np.array([1,2,3,4])
arr.size

4

In [45]:
arr.ndim

1

In [48]:
a = (5,)
type(a)

tuple

In [46]:
arr.shape

(4,)

In [52]:
rgb_image = np.array([
    [[255, 0, 0],
     [0, 255, 0],
     [0, 0, 255]],

    [[255, 255, 0],
     [255, 0, 255],
     [0, 255, 255]],
     ])

In [53]:
rgb_image.shape

(2, 3, 3)

In [54]:
arr.dtype

dtype('int64')

In [60]:
arr = np.array([1, 127, 3], dtype = 'int32')
arr.dtype

dtype('int32')

In [61]:
arr_2d = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
    )
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [62]:
arr_2d.size

6

In [63]:
arr_2d.shape

(2, 3)

In [64]:
arr_2d.ndim

2

In [65]:
arr_2d = np.zeros((5, 3))
print(arr_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [66]:
arr_2d.shape

(5, 3)

In [67]:
arr_2d.ndim

2

# Array Operations

## Aggregations and reductions

Common methods:
- `max`: maximum value
- `min` : minimum value
- `argmax` : index of maximum value
- `argmin` : index of minimum value
- `sum` : sum of values
- `mean` : mean (average) of values
- `std` : standard deviation
- `var` : variance

These use the `axis` parameter to compute along rows or columns.


In [77]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 1, 1])


In [76]:
a = [1,2,3]
b = [2,2,2]
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])

print(c)

[2, 4, 6]


In [79]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])

arr1 * arr2

array([2, 4, 6])

In [80]:
arr1 ** 2

array([1, 4, 9])

In [81]:
arr1.max()

np.int64(3)

In [82]:
np.max(arr1)

np.int64(3)

In [83]:
arr1.argmax()

np.int64(2)

In [84]:
arr1.mean()

np.float64(2.0)

In [85]:
arr2 = np.full((3, 4), 2)
arr2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
arr2.sum(axis=0)

np.int64(24)

In [88]:
arr2.max()

np.int64(2)

## Copying vs views and structural operations

- Indexing and slicing often return views (share memory) not copies.
- Use `.copy()` to force a real copy.
- Structural operations: `append`, `insert`, `delete` return new arrays (they do not modify in place).


In [90]:
arr2d = rng.integers(0, 20, (3, 4))
print(arr2d)

[[10 19 13  0]
 [11  4 13 12]
 [10 19  2  2]]


In [92]:
arr = rng.integers(0, 20, 18)
print(arr)

[ 7 12  2  4 12  0 17 14 12 13  7  8  3  5 10  6  1  4]


In [94]:
arr.reshape(9, 2)

array([[ 7, 12],
       [ 2,  4],
       [12,  0],
       [17, 14],
       [12, 13],
       [ 7,  8],
       [ 3,  5],
       [10,  6],
       [ 1,  4]])

In [96]:
arr.reshape(6, 3)

array([[ 7, 12,  2],
       [ 4, 12,  0],
       [17, 14, 12],
       [13,  7,  8],
       [ 3,  5, 10],
       [ 6,  1,  4]])

In [104]:
arr.reshape(6, -1)

array([[ 7, 12,  2],
       [ 4, 12,  0],
       [17, 14, 12],
       [13,  7,  8],
       [ 3,  5, 10],
       [ 6,  1,  4]])

In [105]:
print(arr2d)

[[10 19 13  0]
 [11  4 13 12]
 [10 19  2  2]]


In [118]:
arr2d[1, 3]

np.int64(12)

In [121]:
arr2d[1:, 1]

array([ 4, 19])

In [181]:
arr2d = rng.integers(0, 10, (20, 20))
print(arr2d)

[[4 6 5 2 1 7 2 2 7 2 2 4 7 8 0 3 9 1 8 5]
 [7 7 3 4 1 4 5 3 7 7 1 4 2 8 3 1 3 6 8 2]
 [0 9 0 0 8 9 6 6 4 7 4 3 5 9 2 7 3 2 0 2]
 [0 5 2 5 6 2 3 5 3 6 3 7 1 0 9 7 1 8 2 6]
 [0 3 2 3 7 3 6 5 8 3 8 5 0 6 2 7 0 1 0 5]
 [2 5 1 9 2 9 0 4 7 7 2 9 0 0 1 5 5 6 2 1]
 [4 1 1 8 3 9 8 3 0 8 7 8 0 5 5 9 0 4 6 3]
 [7 0 0 6 4 9 3 5 6 6 6 9 8 1 3 1 8 3 7 0]
 [4 5 7 6 2 0 0 1 9 8 1 1 0 7 8 1 8 2 4 3]
 [2 6 9 9 6 9 9 7 8 1 4 8 9 7 6 4 5 8 8 7]
 [1 7 1 5 4 9 0 9 7 4 9 0 5 3 1 5 8 3 7 3]
 [7 7 7 5 8 3 6 9 0 7 3 9 5 1 2 8 9 6 6 2]
 [9 1 8 9 4 9 3 4 0 9 2 2 8 6 1 9 3 2 4 3]
 [5 9 3 1 3 3 8 9 5 5 6 2 8 5 3 4 0 0 8 8]
 [7 4 7 4 1 5 8 1 1 2 3 9 7 1 5 6 4 6 1 8]
 [4 5 8 4 5 5 6 0 2 6 3 3 5 4 9 4 2 0 2 7]
 [4 8 7 4 8 7 8 8 5 0 9 4 2 6 4 1 8 8 8 5]
 [6 5 5 8 4 0 2 8 2 7 3 1 4 1 9 8 3 3 1 2]
 [9 4 5 2 5 5 3 4 4 3 6 2 8 9 7 0 8 8 5 1]
 [8 4 5 5 8 6 4 6 9 2 8 9 5 3 9 8 4 1 5 5]]


In [189]:
arr2d[[0,-1]]

array([[4, 6, 5, 2, 1, 7, 2, 2, 7, 2, 2, 4, 7, 8, 0, 3, 9, 1, 8, 5],
       [8, 4, 5, 5, 8, 6, 4, 6, 9, 2, 8, 9, 5, 3, 9, 8, 4, 1, 5, 5]])

In [203]:
arr2d[[0,-1],[-1, -3]]

array([5, 1])

In [140]:
arr2d < 5

array([[ True,  True,  True, False, False,  True, False, False,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False, False],
       [False, False,  True,  True,  True, False,  True,  True, False,
        False,  True,  True,  True, False, False, False, False,  True,
         True, False],
       [ True,  True, False,  True, False,  True,  True, False,  True,
        False, False, False,  True, False,  True, False, False,  True,
         True, False],
       [False,  True, False,  True,  True, False, False,  True,  True,
        False,  True, False, False,  True, False,  True,  True, False,
         True,  True],
       [False,  True, False, False,  True,  True, False,  True, False,
         True,  True,  True, False, False, False, False,  True, False,
         True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True,  True,
         True, False],
       [ T

In [144]:
arr2d = rng.integers(0, 10, (3, 3))
print(arr2d)

[[5 0 8]
 [6 9 1]
 [4 9 1]]


In [145]:
arr2d < 3

array([[False,  True, False],
       [False, False,  True],
       [False, False,  True]])

In [148]:
arr1d = arr2d[arr2d<3]
arr1d

array([0, 1, 1])

In [149]:
arr1d[2] = 100

In [150]:
arr2d

array([[5, 0, 8],
       [6, 9, 1],
       [4, 9, 1]])

## Sorting arrays
- `array.sort()`: sorts the array in place.
- `np.sort(array)`: returns a sorted copy of the array.

In [151]:
arr

array([ 7, 12,  2,  4, 12,  0, 17, 14, 12, 13,  7,  8,  3,  5, 10,  6,  1,
        4])

In [152]:
arr.sort()

In [153]:
arr

array([ 0,  1,  2,  3,  4,  4,  5,  6,  7,  7,  8, 10, 12, 12, 12, 13, 14,
       17])

In [154]:
arr = rng.integers(0, 10, 20)
arr

array([8, 0, 6, 4, 2, 8, 0, 9, 3, 2, 2, 9, 2, 3, 1, 3, 7, 4, 3, 6])

In [ ]:
sort_arr = np.sort(arr)

array([0, 0, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 6, 6, 7, 8, 8, 9, 9])

In [156]:
arr

array([8, 0, 6, 4, 2, 8, 0, 9, 3, 2, 2, 9, 2, 3, 1, 3, 7, 4, 3, 6])

## Uniqueness
- `np.unique(array)`: returns the unique elements of an array.
- `return_counts=True`: also returns the counts of each unique element.

In [161]:
arr = rng.integers(0, 10, 200)
arr

array([1, 0, 6, 3, 8, 1, 1, 2, 0, 2, 3, 7, 1, 1, 3, 4, 5, 7, 1, 7, 8, 4,
       7, 7, 4, 4, 0, 8, 0, 4, 9, 8, 6, 3, 0, 8, 8, 2, 2, 7, 9, 2, 6, 8,
       1, 3, 7, 9, 5, 2, 9, 3, 8, 6, 6, 5, 2, 3, 6, 4, 2, 4, 5, 1, 0, 1,
       4, 9, 2, 1, 1, 9, 9, 7, 6, 7, 9, 6, 1, 6, 6, 1, 3, 7, 6, 6, 9, 7,
       8, 4, 5, 6, 0, 0, 9, 2, 9, 7, 4, 0, 6, 5, 0, 5, 1, 2, 3, 7, 3, 4,
       5, 0, 8, 9, 9, 1, 2, 1, 8, 6, 7, 3, 3, 1, 5, 0, 3, 6, 6, 8, 3, 8,
       0, 5, 0, 2, 0, 4, 3, 3, 2, 8, 0, 9, 3, 8, 1, 8, 3, 7, 6, 3, 6, 1,
       4, 1, 1, 6, 5, 6, 5, 0, 7, 4, 8, 8, 6, 1, 7, 5, 6, 6, 6, 5, 4, 6,
       2, 5, 8, 4, 4, 9, 8, 5, 0, 9, 8, 3, 0, 7, 2, 4, 8, 0, 9, 1, 0, 3,
       1, 8])

In [163]:
np.unique(arr, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([21, 24, 16, 21, 18, 16, 26, 18, 23, 17]))

# Combining Arrays
- `np.concatenate`: join a sequence of arrays along an existing axis.
- `np.stack`: join a sequence of arrays along a new axis.
- `np.hstack`: stack arrays in sequence horizontally (column-wise).
- `np.vstack`: stack arrays in sequence vertically (row-wise).

In [164]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [167]:
arr1 = np.array([[1, 2],
                 [2, 3]])
arr2 = np.array([[4, 5],
                 [6, 7]])

np.concatenate([arr1, arr2], axis=1)

array([[1, 2, 4, 5],
       [2, 3, 6, 7]])

In [171]:
np.stack([arr1, arr2])

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [176]:
np.stack([arr1, arr2], axis=0)

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [178]:
np.vstack([arr1, arr2])

array([[1, 2],
       [2, 3],
       [4, 5],
       [6, 7]])

## Exercises

Try these exercises. Each has a hidden or following solution cell.

1) Create a 1D array of the even numbers from 2 to 40 inclusive using two different methods.
2) Create a 3x3 identity-like array but with 5s on the diagonal.
3) Generate a 5x4 matrix of random integers from 10 to 99, then compute column-wise max and the index of the min in each row.
4) Given `a = np.arange(24)`, reshape it to shape `(4, 3, 2)`, then compute the sum along axis 2.
5) Concatenate two arrays `p = [1,2,3]` and `q = [4,5,6]` as:
   - a) a single 1D array
   - b) a 2x3 stacked array
   - c) a 3x2 stacked array
6) Split `np.arange(20)` into 3 nearly equal parts and sort each part descending.
7) Demonstrate view vs copy by slicing and modifying the original array vs a copy.

