# Spring of Code - Artificial Intelligence
## Week 04: Exploratory Data Analysis
### Day 02: NumPy

In this lesson, we will learn more about NumPy Arrays.

In [1]:
import numpy as np

In [4]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
len(arr)

20

In [8]:
arr = arr.reshape((4, 5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Indexing and Selection
How to select and modify subsets of data from NumPy arrays.


## Scalar indexing vs slicing
Scalar indexing is used to access a single element in an array, while slicing is used to access a range of elements.

In [11]:
arr[0][1]

np.int64(2)

In [12]:
arr[0, 1]

np.int64(2)

In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
arr[2:, 2:]

array([[13, 14, 15],
       [18, 19, 20]])

In [31]:
arr[:,1]

array([ 2,  7, 12, 17])

In [33]:
arr[2,:]

array([11, 12, 13, 14, 15])

## Multidimensional indexing: row/column order
In NumPy, when working with multidimensional arrays, it's important to understand the order in which elements are indexed. NumPy uses a row-major order (C-style) for indexing, meaning that elements are stored row by row.

In [34]:
arr[0] # returns first row

array([1, 2, 3, 4, 5])

## Fancy indexing (integer arrays)
Fancy indexing is a way to access specific elements of an array using integer arrays (or lists) as indices. This allows for more flexible and powerful data selection compared to standard slicing.

In [ ]:
rng = np.random.default_rng(seed = 42)

integers = rng.integers(0, 20, (4, 6))
integers

array([[ 1, 15, 13,  8,  8, 17],
       [ 1, 13,  4,  1, 10, 19],
       [14, 15, 14, 15, 10,  2],
       [16,  9, 10,  7,  3, 18]])

In [56]:
integers[[0, 3, 2]]

array([[ 1, 15, 13,  8,  8, 17],
       [16,  9, 10,  7,  3, 18],
       [14, 15, 14, 15, 10,  2]])

In [54]:
integers[[0, 3, 2], [1, 2, 0]]

array([15, 10, 14])

## Boolean masks
Boolean masks are arrays of boolean values (True/False) that can be used to select elements from another array based on certain conditions. This technique is useful for filtering data.


In [57]:
integers

array([[ 1, 15, 13,  8,  8, 17],
       [ 1, 13,  4,  1, 10, 19],
       [14, 15, 14, 15, 10,  2],
       [16,  9, 10,  7,  3, 18]])

In [58]:
mask = integers < 5

In [59]:
mask

array([[ True, False, False, False, False, False],
       [ True, False,  True,  True, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False,  True, False]])

In [63]:
# integers[mask]
integers[integers < 2]

array([1, 1, 1])

In [69]:
integers[integers % 2 == 0] =  integers[integers % 2 == 0] + 1


In [70]:
integers

array([[ 1, 15, 13,  9,  9, 17],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

## In-place assignment with selection
In-place assignment allows you to modify specific elements of an array directly using indexing or boolean masks. This is useful for updating values without creating a new array.

In [71]:
integers

array([[ 1, 15, 13,  9,  9, 17],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [72]:
np.array([1, 2, 3]) + 1

array([2, 3, 4])

In [76]:
integers[0] = 20

In [77]:
integers

array([[20, 20, 20, 20, 20, 20],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [78]:
integers[0, :2] = -1

In [79]:
integers

array([[-1, -1, 20, 20, 20, 20],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

# Views vs Copies

- Slices are typically views: they reference the same memory as the original array.
- Fancy indexing and boolean masks produce copies: independent memory.
- Use `.copy()` to force a copy.
- Inspect the `.base` attribute to see if an array owns its memory (`.base is None`) or is a view of another array.


a = [10, 20, 30, 40]

b = a[0:2].copy()

b = [10, 20]

In [80]:
arr = integers

arr

array([[-1, -1, 20, 20, 20, 20],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [82]:
arr[0] = 30
arr

array([[30, 30, 30, 30, 30, 30],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [83]:
integers

array([[30, 30, 30, 30, 30, 30],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [84]:
arr = integers.copy()

arr

array([[30, 30, 30, 30, 30, 30],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [85]:
arr is integers

False

In [86]:
arr[0] = 0
arr

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [87]:
integers

array([[30, 30, 30, 30, 30, 30],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15, 11,  3],
       [17,  9, 11,  7,  3, 19]])

In [100]:
b = arr[:, :]

In [101]:
b

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15,  0,  0],
       [17,  9, 11,  7,  3, 19]])

In [90]:
b.ndim

2

In [91]:
b[0] = 0

In [92]:
b

array([[ 0,  0],
       [ 3, 19]])

In [93]:
arr

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15,  0,  0],
       [17,  9, 11,  7,  3, 19]])

In [102]:
b.base is None

False

In [95]:
arr.base is None

True

In [96]:
arr2 = arr

arr2.base is None

True

In [97]:
arr2

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15,  0,  0],
       [17,  9, 11,  7,  3, 19]])

In [98]:
c = arr2[:3]
c

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15,  0,  0]])

In [99]:
c.base is None

False

# Broadcasting

Broadcasting lets arrays with different shapes interact by virtually "stretching" dimensions of size 1. Rules (simplified):
- Compare shapes from right to left.
- Dimensions are compatible if equal or either is 1.
- Result shape is the max along each dimension.
- If any pair is incompatible, error.



# Typecasting and dtypes

- Every `ndarray` has a `dtype` (e.g., `int64`, `float32`, `bool`).
- `astype(new_dtype)` returns a copy with converted type.
- Upcasting: mixing `int` and `float` often results in float.
- Beware of overflow when casting from float to int and of truncation.
- Common ML practice uses float32 to save memory and accelerate on GPUs.


In [103]:
a = np.array([1, 2, 3])
b = np.array([1])

a + b

array([2, 3, 4])

In [105]:
np.array([1, 2, 3]) + np.array([2, 2, 2])

array([3, 4, 5])

a -> shape: 3,1
b -> shape: 3

compare a's 1 and b's 3

In [107]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([1, 1, 1])

a + b

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [108]:
c = np.array([
    [1, 2, 3]
    ])
d = np.array([
    [5],
    [6]
    ])

print("C's shape:", c.shape)
print("D's shape:", d.shape)

C's shape: (1, 3)
D's shape: (2, 1)


c = [
    [1, 2, 3],
    [1, 2, 3]
]

d = [
    [5, 5, 5],
    [6, 6, 6]
]

In [110]:
e = c * d
e

array([[ 5, 10, 15],
       [ 6, 12, 18]])

In [111]:
e.shape

(2, 3)

# Saving and Loading Data

- Native binary: `np.save('file.npy', arr)` and `np.load('file.npy')`
- Multiple arrays: `np.savez('file.npz', a=arr1, b=arr2)` → returns dict-like when loading.
- Control dtypes on load where possible for memory.



In [112]:
arr

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15,  0,  0],
       [17,  9, 11,  7,  3, 19]])

In [113]:
np.save('integers.npy', arr)

In [114]:
arr = np.load('integers.npy')
arr

array([[ 0,  0,  0,  0,  0,  0],
       [ 1, 13,  5,  1, 11, 19],
       [15, 15, 15, 15,  0,  0],
       [17,  9, 11,  7,  3, 19]])

In [118]:
arr1 = rng.random((10, 2))
arr1

array([[0.85340307, 0.23393949],
       [0.05830274, 0.28138389],
       [0.29359376, 0.66191651],
       [0.55703215, 0.78389821],
       [0.66431354, 0.40638686],
       [0.81402038, 0.16697292],
       [0.02271207, 0.09004786],
       [0.72235935, 0.46187723],
       [0.16127178, 0.50104478],
       [0.1523121 , 0.69632038]])

In [119]:
arr2 = rng.integers(0, 10, (5, 5))
arr2

array([[4, 4, 1, 3, 2],
       [3, 6, 6, 6, 3],
       [9, 0, 3, 1, 3],
       [9, 3, 9, 4, 6],
       [4, 2, 7, 9, 2]])

In [120]:
np.savez('arrays.npz', a=arr1, b=arr2)


In [123]:
data = np.load('arrays.npz')

In [124]:
type(data)

numpy.lib.npyio.NpzFile

In [125]:
print(data)

NpzFile 'arrays.npz' with keys: a, b


In [126]:
arr1 = data['a']
arr1

array([[0.85340307, 0.23393949],
       [0.05830274, 0.28138389],
       [0.29359376, 0.66191651],
       [0.55703215, 0.78389821],
       [0.66431354, 0.40638686],
       [0.81402038, 0.16697292],
       [0.02271207, 0.09004786],
       [0.72235935, 0.46187723],
       [0.16127178, 0.50104478],
       [0.1523121 , 0.69632038]])

In [127]:
data['b']

array([[4, 4, 1, 3, 2],
       [3, 6, 6, 6, 3],
       [9, 0, 3, 1, 3],
       [9, 3, 9, 4, 6],
       [4, 2, 7, 9, 2]])

In [128]:
data.values()

ValuesView(NpzFile 'arrays.npz' with keys: a, b)

# Practice: Short Exercises

1) Create a 6×6 array and:
   - Set the diagonal to 1 and anti-diagonal to 2 using slicing and fancy indexing.
   - Replace all values > mean with their z-scores (broadcasting) and leave others unchanged.


In [87]:
arr = np.arange(36).reshape((6,6))
arr.dtype

dtype('int64')

In [88]:
arr = arr.astype(dtype=np.float32)
arr

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]], dtype=float32)

In [89]:
arr.dtype

dtype('float32')

In [90]:
arr[[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]] = 1

arr

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  1.,  8.,  9., 10., 11.],
       [12., 13.,  1., 15., 16., 17.],
       [18., 19., 20.,  1., 22., 23.],
       [24., 25., 26., 27.,  1., 29.],
       [30., 31., 32., 33., 34.,  1.]], dtype=float32)

In [91]:
arr.mean()

np.float32(14.75)

In [92]:
arr > arr.mean()

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False]])

In [93]:
greater_than_mean = arr[arr > arr.mean()].copy()
greater_than_mean

array([15., 16., 17., 18., 19., 20., 22., 23., 24., 25., 26., 27., 29.,
       30., 31., 32., 33., 34.], dtype=float32)

In [94]:
arr.std()

np.float32(11.041273)

In [95]:
greater_than_mean = (arr.mean() - greater_than_mean) / arr.std()
greater_than_mean

array([-0.02264232, -0.11321158, -0.20378084, -0.29435012, -0.38491938,
       -0.47548863, -0.6566272 , -0.74719644, -0.8377657 , -0.92833495,
       -1.0189042 , -1.1094735 , -1.290612  , -1.3811814 , -1.4717506 ,
       -1.5623199 , -1.6528891 , -1.7434584 ], dtype=float32)

In [96]:
arr[arr > arr.mean()] = greater_than_mean
arr

array([[ 1.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         5.        ],
       [ 6.        ,  1.        ,  8.        ,  9.        , 10.        ,
        11.        ],
       [12.        , 13.        ,  1.        , -0.02264232, -0.11321158,
        -0.20378084],
       [-0.29435012, -0.38491938, -0.47548863,  1.        , -0.6566272 ,
        -0.74719644],
       [-0.8377657 , -0.92833495, -1.0189042 , -1.1094735 ,  1.        ,
        -1.290612  ],
       [-1.3811814 , -1.4717506 , -1.5623199 , -1.6528891 , -1.7434584 ,
         1.        ]], dtype=float32)

In [97]:
arr.dtype

dtype('float32')

In [100]:
arr = arr.astype(np.int64)
arr

array([[ 1,  1,  2,  3,  4,  5],
       [ 6,  1,  8,  9, 10, 11],
       [12, 13,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0],
       [ 0,  0, -1, -1,  1, -1],
       [-1, -1, -1, -1, -1,  1]])

2) Create a 2D array of shape (N, D) with random integers, standardize per feature using `keepdims=True`. Verify each column mean is ~0 and std is ~1.


In [101]:
arr = rng.integers(0, 10, (5, 5))
arr

array([[6, 7, 5, 4, 1],
       [8, 8, 0, 7, 0],
       [7, 8, 1, 4, 1],
       [5, 9, 0, 3, 9],
       [3, 1, 4, 5, 6]])

In [103]:
arr_mean = arr.mean(axis = 0, keepdims=True)
arr_std = arr.std(axis = 0, keepdims = True)

arr_standardized = (arr - arr_mean) / arr_std
arr_standardized

array([[ 0.11624764,  0.1393466 ,  1.43019388, -0.44232587, -0.68599434],
       [ 1.27872403,  0.48771311, -0.95346259,  1.76930347, -0.97182532],
       [ 0.69748583,  0.48771311, -0.47673129, -0.44232587, -0.68599434],
       [-0.46499055,  0.83607962, -0.95346259, -1.17953565,  1.60065346],
       [-1.62746694, -1.95085244,  0.95346259,  0.29488391,  0.74316054]])

In [105]:
arr_standardized.mean(axis=0)
arr_standardized.std(axis = 0)

array([1., 1., 1., 1., 1.])

3) Save three arrays `A`, `B`, `C` to a single `.npz`, load and reconstruct `A @ B + C`. Use `float32` dtypes.



4) Create a boolean mask that selects rows where the sum is divisible by 3, then set those rows to 0 in-place.

